label true_end:
    "Corto rings the bell again and again, but to no avail."
    "Misato lets herself into his room, slipping the lock as she told Seyton to do."
    misato "They're gone, you know. They took your money."
    corto "{i}How does she know about the money? What the hell was that cat thing? Does she know about the book?{/i}"
    corto "Ahh, Umeji. Come, sit down. {i}How the hell did she get in anyway? Was the cat thing a fluke?{/i}"
    misato "I think not. We've decided that we're leaving."
    misato "All of us."
    corto "{i}Mouthy brat{/i} Umeji, I understand you have some contraband. A lighter, I believe?"
    "Misato says nothing."
    corto "And that furthermore, you girls have been engaging in... unnatural... activities."
    misato "I prefer to call them supernatural."
    corto "I know you want to be a good girl and be in the good graces of the space brothers, which can only happen with a pure soul. So p{i}--wait, what? Supernatural?{/i}"
    corto "...So please hand over the lighter and I will overlook your indiscretions with miss Bruno."
    misato "I'm keeping it. Goodbye, Master Corto."
    "Misato turns toward the door, but is brought short by the hook of Corto's cane on her shoulder."
    corto "You will stay. You're all going to stay. You have been put in my care, and I intend to take care of you."
    # flashes of bloody plastic wrap, a limply dangling arm
    misato "Like you took care of Akiko?"
    corto "{i}How much does she know?{/i}"
    misato "I know about the book."
    "Corto's gaze darts to a black book on his desk."
    corto "{i}She could ruin me.{/i}"
    misato "The cats were not a fluke. And everything I need to ruin you is right there in that book."
    corto "{i}Without that money, I can't even escape{/i}"
    misato "There's no escape for you now."
    "Corto grabs Misato's arms roughly, wrenches them behind her back, and quickly ties them behind her back with a scarf. He then gags her, and throws her into the closet."
    corto "I'm locking you in there for your own good!"
    "The closet door is jammed by his cane."
    corto "{i}Jesus christ jesus christ what do I do{/i}"
    "A scratching sound comes from the back of the closet, and Misato crawls closer to hear it. It is a cat, clawing at the back side of a heating vent."
    "Misato tries to turn around enough to get her fingers under the edge of the vent housing. She gets her fingernails under it and nearly loses one before it pops loose enough for the edgeof a finger to fit."
    "Scrambling, slicing her fingertips, she finally pulls it loose enough that the cat's weight is able to push it out. Corto doesn't seem to notice the noise, in his panic."
    "The cat is Kuro. He grabs onto the scarf's knot with his teeth and pulls back with all his might, and it comes loose. Then he mews once and hops back into the vent."
    "The closet door still jammed shut, Misato peers down into the murky depths of the chute, just big enough to fit into. She hears mewing down there."
    misato "{i}Cats only mew to talk to humans, so he must want me down there.{/i}"
    "The mewing became more insistent. She removed her gag and gingerly entered the chute --"
    "-- and promptly slid down two stories into wet muck."
    "She struggles to sit up, wipes off her hands the best she can, then rummages through her vest pockets for the lighter."
    "Click... Click... Click... Whoosh"
    "The flame illuminates a stone-walled room, shin-deep in dirty water. Towering over her, a form like a chair, covered with a tattered shroud."
    "The shroud moves. A rat escapes and runs away across the floating muck, and the Throne is revealed."
    "The Throne is made of hair. It is the hair of its late occupants, woven together as it was still growing from their heads. Their bodies, collapsed beneath vermillion robes, are still shackled at the wrists and ankles."
    "Cats begin slinking around it in a circle, yowling. There are more of them than she has ever seen together."
    "A plop, and then another. Fingerbones are plopping into the water. They float to the surface, in the shape of a skeletal hand, pointing at a spot on the far wall."
    "At that moment, the throne spontaneously blazes."
    "The light illuminates the whole room: the spot on the wall is a boarded up window."
    "Misato wades through the murk, the light dying as the hair is rapidly consumed by the flames. She pries the boards off with dirty, bleeding fingers."
    "Using the lighter again, she checks the space she's just opened up: an unused chimney flue, large enough to fit into, with brick protrusions at regular intervals."
    "She stumbles to get up into the hole, and drops the lighter. She's about to go down to get it, but she sees hundreds of pairs of cat eyes glowing in the dark. They begin to pur in unison."
    "She climbs slowly, crumbling brick against bleeding fingers and raw nail beds, scuffing soaked dress shoes and sending dull shocks through the bruised and blistered feet within."
    "Finally, she sees a light open up before her. The grate, in Corto's room."
    "She hops onto the platform of the unused fireplace, then kicks the grate open."
    "She stands there in front of him, muddy and covered in soot, bleeding finger pointing accusingly like a revenant. In his shock, he drops the black book, which he has just set on fire, onto the thick carpet."
    misato "Do you know why I know all this?"
    "Corto shakes his head timidly, unsure if she is alive or a ghost."
    misato "Because I am a telepath."
    "She runs past him and bursts through the door to nowhere, focusing her whole mind on the intent to transmit."
    misato "{i}THERE'S A FIRE! EVACUATE NOW!{/i}"
    "As she falls, she glimpses a lick of flame through the door she just exited through the corner of her eye, and hears a support collapse, then is overtaken by merciful darkness."
    jump may1
