# This is the midpoint, so we have our "false victory" / "raising the stakes" moment here
label misato_and_akane_love_scene:
    akane "But how did you know?"
    misato "Can you keep a secret?"
    akane "Of course..."
    misato "The truth is, I'm a telepath."
    akane "Really?"
    n "Akane looks excited"
    akane "Send something to my mind!"
    n "Misato shakes her head"
    misato "I've never been able to send. I've only ever recieved."
    akane "Ok, then what am I thinking now?"
    akane "{i}I want to kiss you{/i}"
    misato "... I want to kiss you."
    n "Akane leans in and kisses her deeply, then pulls back slightly, her eyes wide and gentle."
    if not persistent.skip_NSFW:
        n "As though drawn into those dark pools, Misato leans in to return the kiss, tangling her fingers in the brown locks. They tumble onto the bed."
        n "Misato found herself straddling Akane's knee, and ground herself into it. Their mouths reconnected, tongues meeting, before exploring ears, necks, nipples."
        n "As they stroked each other, skin flushed first pink, then, eventually, scarlet. Long fingers explored warm, wet grottoes."
        n "The steady beat of the surf, indistinguishable in their ears from heartbeat or breath, beat both their brains in time."
        n "Soon, a hot pleasurable itch began in Misato's crotch -- or was it Akane's? It was hard to tell anymore. They were no longer so distinguishable."
        n "In their desire they became a single organism: four caressing arms, twenty exploratory fingers, four hungry lips, two questing tongues."
        n "But one buzzing intoxicated brain, "
        n " one ocean of fluids,"
        n " and one single throbbing clit shared between them --"
        n " -- the waves crashing against it quickly reaching high tide and breaking,"
        n " leaving them shipwrecked,"
        extend " wet,"
        extend " naked,"
        extend " gasping on the shore,"
        extend " holding hands."
    else:
        scene black
        with dissolve
        pause 1
        scene white
        with dissolve
        pause 1
    scene akane bedroom
    akane "Wow..."
    n "Akane struggled to catch her breath."
    $ achievement.grant("Goth GF")
    akane "Is this what sex with a telepath is always like?"
    misato "I'm not sure... I'm good at knowing how to please people"
    akane "... I'll say."
    misato "But I think something else was going on there."
    akane "Are you sure you can't transmit?"
    misato "I never have... I think."
    akane "You should give it a try."
    n "Misato took a moment to compose herself."
    akane "I mean, we should give it a try."
    misato "You know, you're the first one I've told."
    akane "Nobody else knows?"
    misato "My sister knows, I think."
    misato "She had... when we were younger, she was kitsuneki."
    akane "Possessed?"
    misato "Yeah. Like, actually possessed, by a fox spirit. Growing up in a home where we all believed in the teachings of Master Corto, I thought it was normal."
    misato "Not just the fox spirit, but telepathy too. I didn't know that kitsuneki was a euphemism for psychosis until that kid on the playground said so."
    misato "It was terrible for Miko, all the bullying. And I punched him out, to stand up for her. But it turned out, much of what I heard him say, nobody else heard."
    misato "That was when I realized that I was special too. Other people couldn't hear what people said when they 'closed their lips'."
    misato "I realized that if I told anybody, I'd be bullied too. So from then on--"
    akane "You used it to blend in."
    misato "To become invisible, indiscernible. To match people's expectations."
    akane "How'd it work out for you?"
    n "Misato let out a single chuckle."
    misato "Not great. I was popular -- loved, even -- or at least something was. The distance between the face I put on for people and how I felt inside grew."
    akane "Kids can be terrible. Some adults, too. But all of us in this dorm are already weirdos. I feel like we all already know the real you, at least a little."
