label march16:
    window hide
    scene white with dissolve
    scene black with dissolve
    centered "{color=#fff}{b}16th March, 2012{/b}{/color}"
    $ day = 1
    call staticIn
    window show
    scene white
    pause 1
    scene akane bedroom
    with fade
    akane "Uuuughhh"
    misato "Good morning, Akane-san..."
    akane "Five more minutes..."
    n "..."
    akane "... Turn out the light, will you?"
    misato "I don't think it's on..."
    akane "How is it so bright then?"
    misato "Beats me. There are no windows in this room."
    n "Akane covers her face with a blanket."
    akane "..."
    n "She throws the blanket off with a huff."
    akane "I guess it's not happening."
    misato "I'm sorry. Did the noises keep you up?"
    akane "No, I was dreaming abou"
    extend "-- noises? What noises?"
    misato "I couldn't get to sleep because I kept hearing banging out in the hall. Some animals must have gotten in."
    n "..."
    play sound "sfx/114683__qat__whack02.mp3" volume 0.1
    n "{size=-10}bang{/size}"
    akane "What was that?"
    misato "... I don't know."
    n "Akane looks around the room before grabbing a steelbox blu-ray collection, holding it up like a shield."
    n "Misato finds a tripod leg and holds it up like a spear, and they tiptoe to the door."
    play sound "sfx/114683__qat__whack02.mp3" volume 0.3
    n "In the hall, the banging is more clearly audible."
    n "They sidle up to the door to the nave."
    n "Akane gives a quick nod and they both burst through the door."
    scene nave
    akane "Freeze! We're ar--"
    n "She kneels, places her box set on the floor, and runs up to one of the girls."
    akane "Hana-chan~"
    n "The girl catches her in a hug, in a practiced manner."
    hanabi "Akane-chan! It's been, what, three days?"
    akane "It would have been two. What happened?"
    hanabi "The storm caused all sorts of flooding, so the bus had to stop for the night."
    hanabi "I stayed at a nice onsen, courtesy of the bus company, with these fine ladies -- Asahara-san, Hinamori-san? This is Akane."
    akane "Just Akane, like Dio."
    yuuko "Pleased to make your acquaintance."
    hikari "Likewise."
    hanabi "Extenuating circumstances make for fast friends, so we've already gotten quite close."
    akane "I've gotten close to Umeji-san here as well."
    n "She holds Misato's arm proprietarily."
    akane "Umeji-san, this is Tamaya Hanabi, my e--"
    hanabi "We're classmates."
    misato "Umeji Misato. A pleasure."
    n "The door opened, and two more came in."
    misato "Miko-chan!"
    misato "Everyone, this is my sister, Miko."
    miko "Yo."
    misato "Miko, this is Akane, and Tamaya-san, and Asahara-san, and Hinamori-san."
    miko "This is Ikuhara."
    akiko "Ikuhara Akiko."
    n "Everyone murmured their greetings to the dour Akiko."
    miko "So Cort... I mean, The Master isn't here yet?"
    akane "Nope. When he comes, he's going to take the top floor."
    akane "Wanna snoop? Now that Hana's here..."
    hanabi "I actually was not trusted with the keys to the top floor. It seems The Master knew someone here would try to tempt me..."
    akane "Oh, I'll tempt you alright..."
    extend " But you have the other keys?"
    hanabi "Yup! Here,"
    n "Hanabi handed out a keyring to each of them, with two keys and a little wooden card inscribed with their name and room number."
    hanabi "The small gold key is for the front door and any cabinets or closets that have locks on them. The bigger silver one is for your own room."
    hanabi "On the back of the card, there's a map of the house itself. Half of you will be through the doors on the right, and half will be on the left."

    comment "XXX Upon waking, Misato & Akane talk about the noise. Akane says (quote from Vampire Doll, re: old houses)."
    comment "XXX They hear noises elsewhere in the building, primed to be freaked out, grab ad-hoc weapons to check it out."
    comment "XXX It's Hanabi, Yuuko, and Hikari. Akane excitedly rushes Hanabi, hugging her, then introduces her. "
    "Hanabi introduces Yuuko and Hikari, who she met when their transportation stopped at the same inn for the night due to flooding."
    comment "XXX Akiko and Miko arrive, and Misato introduces Miko, while Miko introduces Akiko but does not explain how they met. Akiko doesn't talk much, causing awkwardness."
    comment "XXX The group talks about how Corto isn't there yet. They start helping each other move in. Hanabi has keys to various rooms, & distributes them."
    "They work together to make a big meal, using a hot plate in a closet and some cans, and eat it while sitting on the floor in the nave."
    comment "XXX Misato sleeps alone, and again, there's a banging in the hall. She asks the player for advice."
    comment "XXX If she decides to check, she discovers the black cat (Kuro) hunting at this point."
    "She asks what to do, & if she plays with the cat she gets points toward cat affinity & towards affinity with Kuro."
    return
